# Generated by Django 4.2.5 on 2025-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=500)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('oid', models.CharField(blank=True, max_length=150)),
                ('amountpaid', models.CharField(max_length=500, null=True)),
                ('paymentstatus', models.CharField(max_length=20)),
                ('phone', models.CharField(default='', max_length=100)),
                ('or_id', models.CharField(default='', max_length=100)),
                ('update_desc', models.CharField(default='', max_length=5000)),
                ('delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('or_id', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAppointments',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='confirmed', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(choices=[('Matchmaking', 'Matchmaking'), ('Wedding Planning', 'Wedding Planning'), ('Photography', 'Photography'), ('Catering', 'Catering'), ('Venue Booking', 'Venue Booking'), ('Makeup & Styling', 'Makeup & Styling'), ('Music & Entertainment', 'Music & Entertainment')], default='Matchmaking', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='service_providers/')),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('available_days', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('service_area_radius', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BRIDE', 'Bridal Collection'), ('GROOM', 'Groom Collection'), ('JEWELRY', 'Jewelry'), ('FOOTWEAR', 'Footwear'), ('ACCESSORIES', 'Accessories')], max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(null=True)),
                ('fabric', models.CharField(blank=True, max_length=100, null=True)),
                ('sizes_available', models.CharField(max_length=100, null=True)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('custom_sizing_available', models.BooleanField(default=False, null=True)),
                ('alteration_available', models.BooleanField(default=False, null=True)),
                ('main_image', models.ImageField(null=True, upload_to='products/main/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('occasion_type', models.CharField(blank=True, help_text='e.g., Wedding, Reception, Sangeet', max_length=50, null=True)),
                ('style', models.CharField(blank=True, help_text='e.g., Traditional, Modern, Fusion', max_length=50, null=True)),
                ('work_type', models.CharField(blank=True, help_text='e.g., Zardozi, Sequin, Embroidery', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'subcategory'], name='ecommerceap_categor_bbf732_idx'), models.Index(fields=['price'], name='ecommerceap_price_b6bd6b_idx')],
            },
        ),
    ]
