# Generated by Django 4.2.4 on 2023-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='or_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
