# Generated by Django 4.2.4 on 2023-08-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_or_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='or_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
