# Generated by Django 4.2.4 on 2023-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_orderupdate_or_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amountpaid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(max_length=20),
        ),
    ]
