# Generated by Django 4.2.5 on 2023-09-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_alter_orders_amountpaid_alter_orders_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='email',
            field=models.CharField(default='', max_length=90),
        ),
    ]
