# Generated by Django 4.2.5 on 2023-09-06 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_orderupdate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='update_desc',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
